# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Study_in_2022_Spring/Computer_System/Lab_Project/Lab2/Lab2.srcs/sources_1/ip/D_BRAM/D_BRAM.xci
# IP: The module: 'D_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study_in_2022_Spring/Computer_System/Lab_Project/Lab2/Lab2.gen/sources_1/ip/D_BRAM/D_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'D_BRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Study_in_2022_Spring/Computer_System/Lab_Project/Lab2/Lab2.srcs/sources_1/ip/D_BRAM/D_BRAM.xci
# IP: The module: 'D_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Study_in_2022_Spring/Computer_System/Lab_Project/Lab2/Lab2.gen/sources_1/ip/D_BRAM/D_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'D_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
